name: .NET Core Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    env: 
      DOTNET_VERSION: 3.1.301
      PACKAGE_PATH: $GITHUB_WORKSPACE/artifacts/build/
      PACKAGE_SOURCE: https://nuget.pkg.github.com/stize/index.json
      PACKAGE_VERSION: ${GITHUB_REF##*/v} # Release tags should allways start with "v". e.g. "v0.0.1-alpha"
    defaults:
      run:
        shell: bash
        working-directory: src/Infrastructure    

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:Version=${{ env.PACKAGE_VERSION }} --configuration Release --no-restore 
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --no-restore -p:Version=${{ env.PACKAGE_VERSION }}
    - name: Push nuget packages
      run: |
          echo Packages to publish:
          ls -o ${{ env.PACKAGE_PATH}}*.*nupkg
          until dotnet nuget push "${{ env.PACKAGE_PATH}}*.nupkg" --api-key ${{ secrets.PACKAGE_TOKEN }} --source ${{env.PACKAGE_SOURCE}}; do echo "Retrying"; sleep 1; done
          until dotnet nuget push "${{ env.PACKAGE_PATH}}*.snupkg" --api-key ${{ secrets.PACKAGE_TOKEN }} --source ${{env.PACKAGE_SOURCE}}; do echo "Retrying"; sleep 1; done