name: .NET Core Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      PACKAGE_SOURCE: https://nuget.pkg.github.com/stize/index.json
      PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOTNET_VERSION: 3.1.301
    defaults:
      run:
        shell: bash
        working-directory: src/Infrastructure    

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - uses: thefringeninja/action-minver@2.0.0-preview1
      name: run minver
      id: version
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --no-restore -p:PackageVersion=${{steps.version.outputs.version}}
    - name: push nuget.org
      run: |
          until dotnet nuget push "./artifacts/build/*.*nupkg" --api-key ${{ env.PACKAGE_TOKEN }} --skip-duplicate --source ${{env.PACKAGE_SOURCE}}; do echo "Retrying"; sleep 1; done